version: '3'
services:
  api:
    build:
      context: .
    environment:
      JAVA_ENV: development

    ports:
    - "4000:8080"
    links:
    - mysql
    - rabbitmq
    - mongo
    - zookeeper
    - kafka

  mysql:
    image: mysql:8.0.16
    ports:
    - "3306:3306"
    restart: always
    volumes:
    - mydata:/var/lib/mysq
    environment:
      MYSQL_ROOT_PASSWORD: wallet
      MYSQL_USER: wallet

  rabbitmq:
    image: rabbitmq:3.8.0-beta.4-management-alpine
    ports:
    - "5672:5672"
    - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: wallet
      RABBITMQ_DEFAULT_PASS: wallet

  mongo:
    image: mongo:4.0.10
    ports:
    - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: wallet
      MONGO_INITDB_ROOT_PASSWORD: wallet

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  mydata: